In [3]:
import numpy as np
import scipy as sp
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
digits = datasets.load_digits()

In [5]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [6]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [8]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [10]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

In [11]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
clf.predict(digits.data[[-1]])

array([8])

In [17]:
from sklearn import svm, datasets
import pickle

In [18]:
clf = svm.SVC()
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
clf.predict(X[[1,50,100]])

array([0, 1, 2])

In [48]:
pickle.dump(clf, open('iris-svm1.pkl', 'wb'))

In [49]:
clf2 = pickle.load(open('iris-svm1.pkl', 'rb'))

In [50]:
clf2.predict(X[[1,50,100]])

array([0, 1, 2])

In [55]:
from sklearn.externals import joblib
joblib.dump(clf, 'iris-svm1.clf')

['iris-svm1.clf']

In [56]:
clf2 = joblib.load('iris-svm1.clf')
clf2.predict(X[[1,50,100]])

array([0, 1, 2])